# Site settings
title: Eat &#9900 Sleep &#9900 Code
email: maxking@hotmail.co.in
author: John Otander
description: "maxking's rants and experiments"
baseurl: ""
url: "http://asynchronous.in"
animated: False


# Build settings
markdown: kramdown
permalink: pretty
paginate: 10
sass:
  compressed: true
