auto: true
lsi: false
pygments: true
exclude: README.markdown
permalink: /:title.html
markdown: rdiscount
name: abhilash's blog
description: This is the official blog of Abhilash Raj(raj.abhilash1@gmail.com)
url: http://maxking.github.com