# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: maxking's blog
email: maxking@asynchronous.in
description: >
  experiments, rants and nonsense
logo: "assets/images/logo.png"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://asychronous.in" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'Abhilash Raj'
bio: >
  Open source enthusiast. <a href="list.org">GNU Mailman</a> core developer.
  Loves Python. Lazy person. TV Series Maniac.
  
author_image: "assets/images/author.png"
twitter_username: _maxking_
github_username:  maxking

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
