baseURL = 'https://asynchronous.in'
languageCode = 'en-us'
title = "maxking's blog"
theme = "gokarna"

enableRobotsTXT = true

[markup]
  [markup.highlight]
  lineNos = true
  lineNumbersInTable = false
  noClasses = false


[params]
  description = "Ramblings and tech things"
  title = "maxking's blog"
  [author]
  name = "Abhilash Raj"
  showPostsOnHomePage = "recent"
  footer = "Abhilash Raj"
  togglePreviousAndNextButtons = "true"


[menu]
  [[menu.main]]
    # Unique identifier for a menu item
    identifier = "posts"

    url = "/posts/"

    # You can add extra information before the name (HTML format is supported), such as icons
    pre = ""

    # You can add extra information after the name (HTML format is supported), such as icons
    post = ""

    # Display name
    name = "Posts"

    # Weights are used to determine the ordering
    weight = 1

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2

  [[menu.main]]
    identifier = "github"
    url = "https://github.com/maxking"
    weight = 3

    # We use feather-icons: https://feathericons.com/
    pre = "<span data-feather='github'></span>"
